
server:
  port: 8080
spring:
  application:
    name: netdev-monitor
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mariadb.xy.dev2:3306/netdevice-two?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: xy
    password: xy@root
  websocket:
    #整个项目中此端口不可占用，否导致websocket不可用
    port: 8888

mybatis-plus:
  mapper-locations: classpath*:com/xy/netdev/**/xml/*Mapper.xml
  typeAliasesPackage: com.xy.netdev.**.entity

snmp:
  listenAddress: 172.21.2.100/161
  targetAddress: 172.21.2.100

swagger:
  enable: true
